//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS_CITAS.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citas
    {
        public int Id { get; set; }
        public int PacienteId { get; set; }
        public int MedicoId { get; set; }
        public System.DateTime FechaHora { get; set; }
        public string Lugar { get; set; }
        public string Estado { get; set; }
        public string Motivo { get; set; }
        public string Notas { get; set; }
    }
}
